version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: data_ingest_postgres
    environment:
      POSTGRES_DB: data_ingest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: data_ingest_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=data_ingest_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - PORT=3000
      - NODE_ENV=production
      - ALLOWED_ORIGINS=*
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./input_file:/app/input_file:ro

volumes:
  postgres_data:
